"""
Django settings for edynx_backend project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%9*+8i4lcc9$==%r=4kmyjpk!@*ya7to))kyxupzthdllq+y(s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '192.168.237.107', '192.168.2.33', '192.168.108.107', '192.168.33.107', '192.168.83.107', '192.168.191.107', '192.168.69.107', '172.20.10.3']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # 'channels',  # Temporarily disabled - install with: pip install channels
    'users',
    'attendance',
    'announcements',
    'edynx_admin',
    'chat',
    'face_recognition',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'edynx_backend.middleware.JWTRoleMiddleware',
    'edynx_backend.middleware.RoleValidationMiddleware',
    'edynx_backend.middleware.RoleBasedAccessMiddleware',
    'edynx_backend.middleware.DataFilterMiddleware',
    'edynx_backend.middleware.AuditLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edynx_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edynx_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Biometric Authentication Settings
BIOMETRIC_SALT = 'edynx_secure_biometric_salt_2024_change_in_production'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(hours=24),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_PREFLIGHT_MAX_AGE = 86400
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8081",
    "http://127.0.0.1:8081",
    "http://localhost:8082",
    "http://127.0.0.1:8082",
    "exp://localhost:8081",
    "exp://localhost:8082",
    # Current mobile network IP (updated)
    "exp://192.168.69.107:8081",
    "exp://192.168.69.107:8082", 
    "http://192.168.69.107:8081",
    "http://192.168.69.107:8082",
    # Previous mobile network IP
    "exp://192.168.108.107:8081",
    "exp://192.168.108.107:8082", 
    "http://192.168.108.107:8081",
    "http://192.168.108.107:8082",
    # Previous mobile network IPs
    "exp://192.168.237.107:8081",
    "exp://192.168.237.107:8082",
    "http://192.168.237.107:8081",
    "http://192.168.237.107:8082",
    # Previous mobile device connections
    "exp://192.168.2.33:8081",
    "exp://192.168.2.33:8082",
    "http://192.168.2.33:8081",
    "http://192.168.2.33:8082",
    "exp://192.168.33.107:8081",
    "exp://192.168.33.107:8082",
    "http://192.168.33.107:8081",
    "http://192.168.33.107:8082",
    "exp://192.168.83.107:8081",
    "exp://192.168.83.107:8082",
    "http://192.168.83.107:8081",
    "http://192.168.83.107:8082",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Crispy Forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Geolocation Settings
SCHOOL_LOCATION = {
    'latitude': 3.8134061130704993,  # Nkol Anga'a, Yaoundé, Cameroon
    'longitude': 11.557817151231376,  # Route de Mfou
    'radius_meters': 500,  # Students must be within 500 meters to mark attendance
    'name': 'IAI School Campus - Nkol Anga\'a'  
}

# Face Recognition API Settings
# AWS Rekognition
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', 'your-aws-access-key')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', 'your-aws-secret-key')
AWS_REGION = os.getenv('AWS_REGION', 'us-east-1')

# Azure Face API
AZURE_FACE_API_KEY = os.getenv('AZURE_FACE_API_KEY', 'your-azure-face-api-key')
AZURE_FACE_ENDPOINT = os.getenv('AZURE_FACE_ENDPOINT', 'https://your-region.api.cognitive.microsoft.com/')

# Google Cloud Vision
GOOGLE_APPLICATION_CREDENTIALS = os.getenv('GOOGLE_APPLICATION_CREDENTIALS', 'path/to/your/service-account-key.json')

# Face Recognition Settings
FACE_RECOGNITION_SETTINGS = {
    'confidence_threshold': 75.0,  # Minimum confidence for face match
    'use_multiple_apis': True,     # Use multiple APIs for better accuracy
    'fallback_enabled': True,      # Enable fallback to local recognition
    'max_face_size_mb': 5,         # Maximum image size in MB
}

# Location Validation Settings
LOCATION_VALIDATION = {
    'enabled': True,
    'strict_mode': False,  # If True, attendance only allowed within radius
    'warning_distance': 1000,  # Show warning if beyond this distance (meters)
    'offline_mode_enabled': True,  # Allow attendance when location unavailable
}

# Biometric Authentication Settings
BIOMETRIC_SALT = os.environ.get('BIOMETRIC_SALT', 'edynx_biometric_salt_change_in_production_2024')
BIOMETRIC_SETTINGS = {
    'enabled': True,
    'fallback_to_camera': True,  # Allow fallback to camera if biometric fails
    'require_device_security': True,  # Require device to have security enabled
    'max_biometric_attempts': 3,  # Maximum biometric attempts before fallback
    'biometric_timeout': 30,  # Timeout for biometric authentication in seconds
}
