# Generated by Django 4.2.23 on 2025-08-23 23:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognitionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_threshold', models.FloatField(default=0.6, help_text='Threshold for face recognition matching (lower = more strict)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('min_image_width', models.IntegerField(default=200, help_text='Minimum image width in pixels')),
                ('min_image_height', models.IntegerField(default=200, help_text='Minimum image height in pixels')),
                ('max_image_size', models.IntegerField(default=5242880, help_text='Maximum image size in bytes (5MB)')),
                ('min_face_size', models.IntegerField(default=50, help_text='Minimum face size in pixels')),
                ('max_faces_allowed', models.IntegerField(default=1, help_text='Maximum number of faces allowed in image')),
                ('max_attempts_per_minute', models.IntegerField(default=5, help_text='Maximum attempts per minute per IP')),
                ('max_failed_attempts', models.IntegerField(default=3, help_text='Maximum failed attempts before lockout')),
                ('lockout_duration', models.IntegerField(default=300, help_text='Lockout duration in seconds')),
                ('enable_face_recognition', models.BooleanField(default=True)),
                ('enable_logging', models.BooleanField(default=True)),
                ('enable_image_storage', models.BooleanField(default=False, help_text='Store face images for debugging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Face Recognition Settings',
                'verbose_name_plural': 'Face Recognition Settings',
                'db_table': 'face_recognition_settings',
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('registration', 'Face Registration'), ('update', 'Face Update'), ('deletion', 'Face Deletion'), ('authentication', 'Authentication'), ('settings_change', 'Settings Change'), ('system_error', 'System Error')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('additional_data', models.TextField(blank=True, help_text='Additional data as JSON', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_admin_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Recognition Audit Log',
                'verbose_name_plural': 'Face Recognition Audit Logs',
                'db_table': 'face_recognition_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_type', models.CharField(choices=[('authentication', 'Authentication'), ('registration', 'Registration'), ('update', 'Update Registration')], max_length=20)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces'), ('low_quality', 'Low Quality Image'), ('no_match', 'No Match Found'), ('error', 'System Error')], max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('image_size', models.IntegerField(blank=True, help_text='Image size in bytes', null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('faces_detected', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Recognition Attempt',
                'verbose_name_plural': 'Face Recognition Attempts',
                'db_table': 'face_recognition_attempts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encoding_data', models.TextField(help_text='Face encoding as JSON string')),
                ('confidence_score', models.FloatField(help_text='Confidence score of the face encoding', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('image_quality', models.FloatField(default=0.0, help_text='Quality score of the source image', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('update_count', models.IntegerField(default=0, help_text='Number of times encoding was updated')),
                ('source_image_width', models.IntegerField(blank=True, null=True)),
                ('source_image_height', models.IntegerField(blank=True, null=True)),
                ('source_image_format', models.CharField(blank=True, max_length=10, null=True)),
                ('face_landmarks_count', models.IntegerField(default=0)),
                ('face_bounding_box', models.TextField(blank=True, help_text='Face bounding box as JSON', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Encoding',
                'verbose_name_plural': 'Face Encodings',
                'db_table': 'face_encodings',
            },
        ),
    ]
