# Generated by Django 4.2.23 on 2025-08-23 11:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('morning', 'Morning Session'), ('afternoon', 'Afternoon Session'), ('evening', 'Evening Session'), ('custom', 'Custom Session')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_sessions',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='attendance.attendancesession')),
            ],
            options={
                'db_table': 'qr_codes',
            },
        ),
        migrations.CreateModel(
            name='PeerAttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scanned_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_scans_received', to=settings.AUTH_USER_MODEL)),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_scans_given', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_attendance_logs', to='attendance.attendancesession')),
            ],
            options={
                'db_table': 'peer_attendance_logs',
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_score', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('success', models.BooleanField()),
                ('image_data', models.TextField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_recognition_logs', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_recognition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'face_recognition_logs',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
            },
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='attendance.class'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('pending', 'Pending Verification')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('face_recognition', 'Face Recognition'), ('qr_code', 'QR Code'), ('peer_scan', 'Peer Scan'), ('manual', 'Manual Entry'), ('justification', 'Absence Justification')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.CreateModel(
            name='AbsenceJustification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='absence_justifications/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justification', to='attendance.attendance')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_justifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_justifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'absence_justifications',
            },
        ),
        migrations.CreateModel(
            name='AttendanceStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_sessions', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('excused_count', models.IntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stats', to='attendance.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_statistics',
                'unique_together': {('student', 'class_obj', 'period_start', 'period_end')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('class_obj', 'date', 'session_type')},
        ),
    ]
