# Generated by Django 4.2.23 on 2025-09-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_enhance_attendance_with_location'),
        ('attendance', '0002_make_attendance_nullable'),
    ]

    operations = [
    ]
